import Image from "next/image"

export default function Navbar () {
    return(
        <div className="bg-white py-5 w-20 h-dvh flex flex-col space-between">
                 <Image
                  src="/logo.svg"
                  alt="Brand Logo"
                  className=""
                  width={40}
                  height={40}
                  priority
                             />
                 <Image
                  src="/category.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                 <Image
                  src="/trend-up.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                 <Image
                  src="/profile-2user.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                 <Image
                  src="/box.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                 <Image
                  src="/discount-shape.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                 <Image
                  src="/info-circle.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                 <Image
                  src="/sun-fill.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                 <Image
                  src="/moon-1.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                 <Image
                  src="/arrow-right.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                 <Image
                  src="/setting-2.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                 <Image
                  src="/logout.svg"
                  alt=""
                  className=""
                  width={24}
                  height={24}
                  priority
                             />
                
              
        </div>
    )
}